export const commonPasswords = new Set([
  "password", "password1", "password123", "password1234",
  "123456", "12345678", "123456789", "1234567890",
  "qwerty", "qwerty123", "qwertyuiop",
  "abc123", "abcdef", "abcd1234",
  "letmein", "welcome", "welcome1", "welcome123",
  "admin", "admin123", "administrator",
  "login", "master", "passw0rd",
  "111111", "000000", "123123", "121212",
  "sunshine", "princess", "football", "baseball", "soccer",
  "monkey", "dragon", "shadow", "michael", "jennifer",
  "iloveyou", "trustno1", "batman", "superman",
  "starwars", "whatever", "hello", "freedom",
  "charlie", "donald", "ashley", "bailey",
  "passpass", "zaq1zaq1", "qazwsx", "password!",
  "test123", "testing", "guest", "sample",
  "changeme", "secret", "pass123", "pass1234",
  "qwerty12", "qwerty1", "1q2w3e4r", "1qaz2wsx",
  "q1w2e3r4", "zxcvbnm", "asdfgh", "asdfghjk",
  "winter2024", "summer2024", "spring2024", "fall2024",
  "winter2025", "summer2025", "spring2025", "fall2025",
  "winter2026", "summer2026", "spring2026", "fall2026",
  "january", "february", "march", "april", "may", "june",
  "july", "august", "september", "october", "november", "december",
  "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday",
  "12345", "123321", "654321", "987654321",
  "password12", "password2", "password3",
  "compaq", "computer", "internet", "server",
  "access", "master1", "magic", "pass",
  "qwertyui", "1234qwer", "zxcvbn",
  "1password", "mypassword", "mypass123",
  "pa55word", "pa55w0rd", "p@ssword", "p@ssw0rd",
  "letmein1", "letmein123", "monkey1", "dragon1",
  "baseball1", "football1", "hockey", "basketball",
  "jordan", "jordan23", "michael1", "mike123",
  "love", "lovely", "lover", "loveme",
  "hottie", "sexy", "princess1", "babe",
  "baby", "angel", "angel1", "angels",
  "buddy", "buddy1", "buddies",
  "password01", "password02", "password10", "password99",
  "secret1", "secret123", "mysecret",
  "fuckoff", "fuckyou", "biteme", "asshole",
  "killer", "killer1", "death", "dead",
  "ninja", "pirate", "zombie", "ghost",
  "god", "jesus", "christ", "blessed",
  "mustang", "harley", "corvette", "ferrari",
  "cowboys", "eagles", "steelers", "patriots",
  "yankees", "redsox", "lakers", "bulls",
  "beer", "coffee", "chocolate", "cookie",
  "matrix", "bond007", "007bond", "james007",
  "chicken", "cheese", "pepper", "ginger",
  "orange", "banana", "apple", "lemon",
  "flower", "garden", "nature", "forest",
  "ocean", "river", "mountain", "sunset",
  "purple", "yellow", "orange1", "green1",
  "red123", "blue123", "black123", "white123",
  "welcome!", "welcome1!", "password!", "123456!",
  "notpassword", "nopassword", "newpassword", "oldpassword",
  "temppass", "temporary", "temp1234",
  "student", "teacher", "school", "college", "university",
  "company", "business", "office", "work",
  "home", "house", "family", "friend",
  "private", "public", "personal",
  "account", "banking", "money", "dollar",
  "security", "secure", "safe", "safety",
  "admin1", "admin12", "admin123!", "root",
  "root123", "superuser", "sysadmin", "operator",
  "spa123", "salon123", "booking", "booking123",
  "service", "services", "customer", "client",
  "staff", "employee", "manager", "owner",
  "dubai", "abudhabi", "uae", "emirates",
  "serene", "serenity", "relax", "relaxing",
  "beauty", "wellness", "health", "fitness",
  "massage", "treatment", "therapy",
]);

export function isCommonPassword(password: string): boolean {
  return commonPasswords.has(password.toLowerCase());
}
